### ISSUE TITLE
not an issue, code review question.

### ISSUE THREAD

**Issue by Acerbic** [dance2die/react-use-localstorage#38]
https://github.com/dance2die/react-use-localstorage/blob/0e0100b64e82bb0b26f814b5895788e626ef635a/src/index.ts#L29

why are you using `value` as a dependency for `handleStorage` callback, instead of `key`?
It seemingly will cause your code to reattach event listener every time the value changes.

I figured you are memoizing event handling, so if `useLocalStorage` is used simultaneously in several components, the state update handing only happened once, but why depend on the current value instead of a stable `key` for this?

@VitorLuizC

**Comment by dance2die** [comment]
Hi @Acerbic 

`handleStorage` is a callback for [Window: storage event](https://developer.mozilla.org/en-US/docs/Web/API/Window/storage_event).   
The reason for the `value` as a dependency is because `storage` event is called whenever local storage value changes.   
`key` is property of `event`, which is not a real dependency because `key` won't change as it's passed once via `useLocalStorage`. The library assumes you call `useLocalStorage` per key.

**Comment by VitorLuizC** [comment]
I also questioned the same in my first PR (https://github.com/dance2die/react-use-localstorage/pull/16#discussion_r292019834). And just to complement what @dance2die answered, dealing with keys that may change also increases complexity, and some decisions about how to update state would have to be made.

**Comment by Acerbic** [comment]
I see, thank you for your time.

**Comment by dance2die** [comment]
You're welcome @Acerbic & thank you @VitorLuizC for following up, as well 😃
