### ISSUE TITLE
Outside module

### ISSUE THREAD

**Issue by krychaxp** [dance2die/react-use-localstorage#43]
When run on next.js : 
import useLocalStorage from "react-use-localstorage";

Console: 'SyntaxError: Cannot use import statement outside a module'

**Comment by dance2die** [comment]
Hi @krychaxp.  

Check out the note on SSR in README: https://github.com/dance2die/react-use-localstorage#note-for-ssr-server-side-rendering

**Comment by olerichter00** [comment]
Hey @dance2die,

I think the problem is caused by this change https://github.com/dance2die/react-use-localstorage/pull/20/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L12.

It changes the main entry point to `dist/react-use-localstorage.esm.js` which won't work with NextJS. 

I provided a PR that uses `dist/index.js` as the main entry point: https://github.com/dance2die/react-use-localstorage/pull/44

------------------------------ 

@krychaxp An easy workaround for NextJS is to use `requre()` inside of your component:

```
const useLocalStorage = require('react-use-localstorage').default
```

**Comment by justin-calleja** [comment]
@olerichter00 using `require` won't solve the problem:

```
webapp/node_modules/react-use-localstorage/dist/react-use-localstorage.esm.js:1
import { useState, useEffect, useCallback } from 'react';
```

i.e. the issue is with `main` being set to `dist/react-use-localstorage.esm.js` for this package and so you'll come across that file's `import` statements anyway even if your code uses `require`.

Also, @dance2die using `useSsrLocalStorage` uses `useLocalStorage` anyway so you'll end up importing it:

```ts
const useSsrLocalStorage = (
  key: string,
  initial: string
): [string, React.Dispatch<string>] => {
  return typeof window === 'undefined'
    ? [initial, (value: string) => undefined]
    : useLocalStorage(key, initial);
};
```

**Comment by justin-calleja** [comment]
In case anyone else needs a `v3.5.0` of this package with `main` pointing to `cjs` build: https://www.npmjs.com/package/@justinc/react-use-localstorage
