### ISSUE TITLE
Package does not contains typings for Typescript development

### ISSUE THREAD

**Issue by TheAifam5** [dance2die/react-use-localstorage#9]
Hey!
I see that the project is written using TypeScript. I wonder why there is no typings for that.
You can generate typings by settings `declarationDir/declarationMap` and adding to `package.json` that line: `"types": "./dist/main.d.ts"`.

Regards,
TheAifam5

**Comment by dance2die** [comment]
Thanks @TheAifam5~ 🙂

As I am still new to TypeScript, I totally forgot about generating the type definitions 😅

I will add the typings.

**Comment by dance2die** [comment]
@allcontributors please add @TheAifam5 for ideas

**Comment by dance2die** [comment]
@TheAifam5 I've added typings & sourcemap in the distribution

https://unpkg.com/react-use-localstorage@2.4.1/dist/

Also learned that not specifying the return type explicitly, TypeScript generated wrong return type of `(string | (item: string) => void)` instead of `[string | (item: string) => void]` so fixed it as well in `v2.4.1` 🙂
